export { default as LoginForm } from './login/LoginForm'
export { default as RegistrationForm } from './register/RegistrationForm'
export { default as PrincipalPageCustomer } from './customer-pages/principal/PrincipalPageCustomer'
export { default as PrincipalPageWorker } from './worker-pages/principal/PrincipalPageWorker'
export { default as AvailableServices } from './customer-pages/available-services/AvailableServices'
